### ISSUE TITLE
run build command failed.

### ISSUE THREAD

**Issue by sendreams** [Esri/java-gradle-starter-project#42]
after run 'build' from gradle , show the error:

`C:\Users\Administrator\git\java-gradle-starter-project\src\main\java\module-info.java:17: 错误: 找不到模块: com.esri.arcgisruntime`

i have already run 'copyNatives' command. and the directory 'C:\Users\Administrator\.arcgis\200.4.0' already have some files.
`12:35:23: Executing 'copyNatives'...

> Task :copyNatives

BUILD SUCCESSFUL in 4s
1 actionable task: 1 executed
12:35:28: Execution finished 'copyNatives'.
`

**Comment by sendreams** [comment]
Case solved! It turns out the issue was due to Gradle not being configured to use JDK 17.

**Comment by mbcoder** [comment]
@sendreams glad you resolved the issue.  We support Java 17 and 21 with our latest 200.4 [release](https://developers.arcgis.com/java/system-requirements/system-requirements-for-200-4/).
